name = "vega-vireos"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[triggers]
crons = ["0 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "birds"
database_id = "cca2c12e-adde-4ae8-917a-b1466551c3e0"

[assets]
directory = "./public"

[observability]
[observability.logs]
enabled = true
invocation_logs = true
