build:
    docker compose build

start:
    docker compose --env-file .env.local up -d

start-prod:
    docker compose -f docker-compose.yml --env-file .env.prod up -d

stop:
    docker compose down

poll:
    docker compose kill --signal SIGUSR1 bird-sync

logs:
    docker compose logs -f
